-  name: install maven to code compile
   ansible.builtin.yum:
      name: maven
      state: installed

-  name: Import app-preq role
   ansible.builtin.import_role:
      name: common
      tasks_from: app-preq.yml

#for nexus
-  name: Install maven dependencies  ( code compile )
   ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
   args:
      chdir: /app

-  name: Install mysql client server
   ansible.builtin.yum:
      name: mysql
      state: installed

-  name: mongo schema load
   ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{env}}.shipping.DB_HOST', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.master_username', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.master_password', region='us-east-1' ) }} < /app/schema/{{ component }}.sql

-  name: Import a service role
   ansible.builtin.import_role:
      name: common
      tasks_from: service.yml