-  name: shipping configuration
   hosts: all
   become: true
   tasks:
      -  name: install maven to code compile
         ansible.builtin.yum:
            name: maven
            state: installed

      -  name: configuration of app pre-req
         ansible.builtin.import_tasks: app-preq.yml

      -  name: Install maven dependencies  ( code compile )
         ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
         args:
            chdir: /app

      -  name: Install mysql client server
         ansible.builtin.yum:
            name: mysql
            state: installed

      -  name: mongo schema load
         ansible.builtin.shell: mysql -h sql.tadikonda.online -uroot -pRoboShop@1 < /app/schema/shipping.sql

      -  name: start service
         ansible.builtin.import_tasks: service.yml
