- name: Install nginx
  ansible.builtin.yum:
     name: nginx
     state: installed

- name: Copy Nginx project config file
  ansible.builtin.copy:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf

- name: Copy Roboshop Reverse proxy config file
  ansible.builtin.template:
     src: roboshop-conf
     dest: /etc/nginx/default.d/roboshop.conf

- name: clean old content
  ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent

- name: Create nginx content directory
  ansible.builtin.file:
     path: /usr/share/nginx/html
     state: directory

- name: Download & extract App content
  ansible.builtin.unarchive:
     src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes

- name: Restart nginx service
  ansible.builtin.systemd:
     name: nginx
     state: restarted
     enabled: true

-  name: Filebeat Setup
   ansible.builtin.import_role:
      name: elk
      tasks_from: filebeat.yml