- name: Install nginx
  ansible.builtin.yum:
     name: nginx
     state: installed

- name: Copy file with owner and permissions
  ansible.builtin.copy:
     src: roboshop-conf
     dest: /etc/nginx/default.d/roboshop.conf

- name: clean old content
  ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent

- name: Create nginx content directory
  ansible.builtin.file:
     path: /usr/share/nginx/html
     state: directory

- name: Download & extract App content
  ansible.builtin.unarchive:
     src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes

- name: Restart nginx service
  ansible.builtin.systemd:
     name: nginx
     state: restarted
     enabled: true