-  name: Import a role
   ansible.builtin.import_role:
      name: common
      tasks_from: nodejs.yml

-  name: Filebeat Setup
   ansible.builtin.import_role:
      name: elk
      tasks_from: filebeat.yml