-  name: config of nodejs repo
   ansible.builtin.shell: yum module disable nodejs -y ; yum module enable nodejs:18 -y

-  name: Install Nodejs
   ansible.builtin.yum:
      name: nodejs
      state: installed

-  name: configuration of app pre-req
   ansible.builtin.import_tasks: app-preq.yml

-  name: Install nodejs dependencies  ( code compile )
   ansible.builtin.shell: npm install
   args:
      chdir: /app

-  name: schema setup
   ansible.builtin.import_tasks: mongoschema.yml
   when: schema is defined

-  name: systemd setup
   ansible.builtin.import_tasks: service.yml

