-  name: copy service file
   ansible.builtin.template:
      src: "{{ component }}.service"
      dest: /etc/systemd/system/{{ component }}.service

-  name: Restart service
   ansible.builtin.systemd:
      name: "{{ component }}"
      state: restarted
      enabled: yes
      daemon_reload: yes