-  name: copy service file
   ansible.builtin.copy:
      src: "{{ component }}.service"
      dest: /etc/systemd/system/catalogue.service

-  name: Restart service
   ansible.builtin.systemd:
      name: "{{ component }}"
      state: restarted
      enabled: yes