-  name: copy service file
   ansible.builtin.template:
      src: "{{ component }}.service"
      dest: /etc/systemd/system/{{ component }}.service

-  name: Restart service
   ansible.builtin.systemd:
      name: "{{ component }}"
      state: restarted
      enabled: yes
      daemon_reload: yes

## RSYSLOG Config

-  name: copy service file
   ansible.builtin.template:
      src: "rsyslog.conf"
      dest: /etc/rsyslog.d/roboshop.conf

-  name: Restart service
   ansible.builtin.systemd:
      name: "rsyslog"
      state: restarted
