-  name: copy service file
   ansible.builtin.copy:
      src: "{{ component }}.service"
      dest: /etc/systemd/system/catalogue.service

-  name: Enable a timer unit for dnf-automatic
   ansible.builtin.systemd_service:
      name: "{{ component }}"
      state: restarted
      enabled: yes