groups:
   - name: Alerts
     rules:
     - alert: InstanceDown
       expr: up == 0
       for: 1m
       labels:
         severity: page
       annotations:
         summary: "Instance {{ $labels.name }} down"
         description: "{{ $labels.name }} of job {{ $labels.job }} has been down for more than 1 minutes."