groups:
   - name: Alerts
     rules:
     - alert: InstanceDown
       expr: up == 0
       for: 1m
       labels:
         severity: critical
       annotations:
         summary: "Instance  down"
         description: "has been down for more than 1 minutes."